---
# .. vim: foldmarker=[[[,]]]:foldmethod=marker
#
# tasks file for netdata

# Manage repository [[[1
## Add repository
- name: Add OpenManage repository
  apt_repository:
    update_cache: False
    repo:     '{{ item.repo }}'
    mode:     '{{ item.mode     | d(omit) }}'
    filename: '{{ item.filename | d(omit) }}'
    state:    '{{ item.state    | d("present") }}'
  with_flattened:
    - '{{ openmanage__repositories }}'
  register: openmanage__register_repositories

## Add repository key
- name: Add OpenManage repo key
  apt_key:
    url:       '{{ item.key_url       | d(omit) }}'
    id:        '{{ item.key_id        | d(omit) }}'
    keyserver: '{{ item.key_keyserver | d(omit) }}'
  with_flattened:
    - '{{ openmanage__repositories }}'
  register: openmanage__register_key

## Update cache
- name: Update APT cache
  apt:
    update_cache: True
  when: (openmanage__deploy_state == "present") and
        (openmanage__register_repositories.changed or
           openmanage__register_key.changed)

# Manage packages [[[1
## Manage depencies packages
- name: Ensure dependencies are present
  package:
    name: '{{ item }}'
    state: "present"
    install_recommends: '{{ openmanage__install_recommends | bool }}'
  with_flattened:
    - '{{ openmanage__dep_packages | to_nice_json }}'
  when: (openmanage__deploy_state == "present")

 ## Manage base system packages
- name: Ensure base packages are in there desired state
  package:
    name: '{{ item }}'
    state: '{{ "present" if (openmanage__deploy_state == "present") else "absent" }}'
    install_recommends: '{{ openmanage__install_recommends | bool }}'
  with_flattened:
    - '{{ openmanage__base_packages | to_nice_json }}'

# Executable [[[1
## Fix some permissions
- name: Ensure Executables can be run
  file:
    path: /opt/dell/srvadmin/sbin/racadm-wrapper-idrac7
    mode: 0755

## Fix RAC1170 error
- name: Fix libssl error RAC1170
  file:
    src: "/usr/lib/x86_64-linux-gnu/libssl.so.1.0.2"
    dest: "/opt/dell/srvadmin/lib64/libssl.so"
    state: link
